-- ============================================================
-- BELLEWOOD PHARMACY
-- Anonymous medication search activity
-- No patient names, emails, phone numbers, Rx numbers or PHI.
-- ============================================================

create table if not exists public.medication_search_activity (
  id bigint generated by default as identity primary key,
  search_term text not null,
  matched boolean not null default false,
  result_count integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.medication_search_activity enable row level security;

drop policy if exists "public can insert medication searches"
on public.medication_search_activity;

create policy "public can insert medication searches"
on public.medication_search_activity
for insert
to anon, authenticated
with check (true);

drop policy if exists "authenticated staff can read medication searches"
on public.medication_search_activity;

create policy "authenticated staff can read medication searches"
on public.medication_search_activity
for select
to authenticated
using (true);

create index if not exists medication_search_activity_created_at_idx
on public.medication_search_activity(created_at desc);

create index if not exists medication_search_activity_search_term_idx
on public.medication_search_activity(search_term);
